Repository BaeJunH0/AlumniLink_BE, pull requests merged in 2024-11, with the labels that each got.

#5 refactor : PR 템플릿 이름 소문자로 변경
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: 📗 docs

#6 refactor : PR 템플릿 위치 변경
  .github/pull_request_template.md
Labels: 📗 docs

#7 docs : #3 readme 파일 초안 작성
  README.md
Labels: 📗 docs

#9 Feat : #8 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/sparksInTheStep/webBoard/auth/application/UserService.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/UserCommand.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/UserInfo.java
  src/main/java/com/sparksInTheStep/webBoard/auth/domain/User.java
  src/main/java/com/sparksInTheStep/webBoard/auth/persistent/UserRepository.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/UserController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/dto/UserRequest.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/dto/UserResponse.java
  src/main/java/com/sparksInTheStep/webBoard/auth/util/JwtUtil.java
  src/main/java/com/sparksInTheStep/webBoard/auth/util/Token.java
  src/main/java/com/sparksInTheStep/webBoard/global/annotation/AuthorizedUser.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/resources/application.properties
Labels: 📗 docs, 🛠 feat, 📞 API

#10 Docs : 풀 리퀘스트 연습용
  README.md
Labels: 📗 docs

#13 Refactor : #12 로그인 기능 리펙터링 수행
  src/main/java/com/sparksInTheStep/webBoard/auth/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/UserService.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/MemberCommand.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/MemberInfo.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/UserCommand.java
  src/main/java/com/sparksInTheStep/webBoard/auth/application/dto/UserInfo.java
  src/main/java/com/sparksInTheStep/webBoard/auth/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/auth/persistent/MemberRepository.java
  src/main/java/com/sparksInTheStep/webBoard/auth/persistent/UserRepository.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/MemberController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/dto/MemberResponse.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/dto/UserRequest.java
  src/main/java/com/sparksInTheStep/webBoard/auth/token/JwtTokenProvider.java
  src/main/java/com/sparksInTheStep/webBoard/auth/token/Token.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/resources/application.properties
  src/test/java/com/sparksInTheStep/webBoard/auth/application/MemberServiceTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/domain/MemberTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/persistent/MemberRepositoryTest.java
Labels: 👎 fix, 🏸 refactor

#16 Fix : #15 멤버 도메인의 문제를 해결
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/MemberController.java
Labels: 👎 fix

#17 Fix : #16 디렉토리 명 변경에 따른 문제 해결
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
Labels: 👎 fix

#18 Fix : 로그인 관련 문제 해결
  src/main/java/com/sparksInTheStep/webBoard/auth/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/global/configurer/WebConfig.java
Labels: 👎 fix

#19 Feat/#11 content init
  src/main/java/com/sparksInTheStep/webBoard/WebBoardApplication.java
  src/main/java/com/sparksInTheStep/webBoard/auth/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/content/controller/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/content/controller/dto/PostRequest.java
  src/main/java/com/sparksInTheStep/webBoard/content/controller/dto/PostResponse.java
  src/main/java/com/sparksInTheStep/webBoard/content/domain/Post.java
  src/main/java/com/sparksInTheStep/webBoard/content/domain/TimeStamp.java
  src/main/java/com/sparksInTheStep/webBoard/content/persistence/PostRepository.java
  src/main/java/com/sparksInTheStep/webBoard/content/service/PostService.java
  src/main/java/com/sparksInTheStep/webBoard/content/service/dto/PostCommand.java
  src/main/java/com/sparksInTheStep/webBoard/content/service/dto/PostInfo.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/resources/application.properties
Labels: 🛠 feat

#33 Feat : #26 swagger로 API 명세를 작성해요
  build.gradle
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminApiController.java
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminPageController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/AuthApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/AuthController.java
  src/main/java/com/sparksInTheStep/webBoard/comment/application/CommentService.java
  src/main/java/com/sparksInTheStep/webBoard/comment/application/dto/CommentInfo.java
  src/main/java/com/sparksInTheStep/webBoard/comment/domain/Comment.java
  src/main/java/com/sparksInTheStep/webBoard/comment/persistent/CommentRepository.java
  src/main/java/com/sparksInTheStep/webBoard/comment/presentation/CommentApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/comment/presentation/CommentController.java
  src/main/java/com/sparksInTheStep/webBoard/comment/presentation/dto/CommentResponse.java
  src/main/java/com/sparksInTheStep/webBoard/global/annotation/AuthorizedUser.java
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/CommentErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/PostErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberCommand.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberInfo.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/member/persistent/MemberRepository.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberResponse.java
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/Post.java
  src/main/java/com/sparksInTheStep/webBoard/post/persistence/PostRepository.java
  src/main/java/com/sparksInTheStep/webBoard/post/service/PostService.java
  src/main/java/com/sparksInTheStep/webBoard/post/service/dto/PostInfo.java
  src/test/java/com/sparksInTheStep/webBoard/auth/application/MemberServiceTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/domain/MemberTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/persistent/MemberRepositoryTest.java
Labels: 📗 docs, 🛠 feat

#34 Feat/post swagger
  build.gradle
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/CustomExceptionHandler.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/post/controller/dto/PostRequest.java
Labels: 🛠 feat

#36 Feat : #35 베포를 위한 설정을 해요
  src/main/java/com/sparksInTheStep/webBoard/global/configurer/WebConfig.java
Labels: 🛠 feat

#38 Feat : #37 - cicd 구현
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🛠 feat

#39 fix : 버전을 찾지 못하는 부분 재설정
  .github/workflows/deploy.yml
Labels: 🛠 feat

#40 fix : 버전을 찾지 못하는 부분 재설정
  .github/workflows/deploy.yml
Labels: 👎 fix

#41 fix : 이미지 버전을 못찾는 문제 해결
  Dockerfile
Labels: 👎 fix

#42 fix : 내부 디렉토리 인식을 못하는 문제 해결
  Dockerfile
Labels: 👎 fix

#57 Refactor : Post Enum 변수 변경
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/PostType.java
Labels: 🏸 refactor

#58 fix : 명세에 맞지 않는 spec 사항 변경
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostApiSpec.java
Labels: 👎 fix

#60 feat : #59 하나의 게시글을 조회하는 기능 구현
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/post/controller/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/post/service/PostService.java
Labels: 🛠 feat, 📞 API
