Repository BaeJunH0/AlumniLink_BE, pull requests merged in 2025-01, with the labels that each got.

#81 [Feat] #75 유저 취업 유무 정보 추가
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberCommand.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberInfo.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberController.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberResponse.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
Labels: 🛠 feat, 📞 API

#84 [Docs] #77 리드미 업데이트
  README.md
Labels: 📗 docs

#83 [Feat] #76 프로젝트 도메인과 기능 구현
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/ProjectErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/ProjectService.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectCommand.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectInfo.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/JoinedProject.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/Project.java
  src/main/java/com/sparksInTheStep/webBoard/project/persistent/JoinedProjectRepository.java
  src/main/java/com/sparksInTheStep/webBoard/project/persistent/ProjectRepository.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/ProjectApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/ProjectController.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectRequest.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectResponse.java
Labels: 🛠 feat, 📞 API

#85 [2025.01.01] dev 진행 내역 main에 머지
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/ProjectErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberCommand.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberInfo.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberController.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberResponse.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/PostType.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/ProjectService.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectCommand.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectInfo.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/JoinedProject.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/Project.java
  src/main/java/com/sparksInTheStep/webBoard/project/persistent/JoinedProjectRepository.java
  src/main/java/com/sparksInTheStep/webBoard/project/persistent/ProjectRepository.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/ProjectApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/ProjectController.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectRequest.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectResponse.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
Labels: 🧷 Git

#86 [Refactor] little refactoring
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/ProjectApiSpec.java
  src/main/resources/static/js/login.js
Labels: 🏸 refactor

#87 [Refactor]: 변경점 반영 및 버그 수정
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/resources/static/js/login.js
Labels: 👎 fix, 🏸 refactor

#95 개발 내용 반영
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminApiController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/AuthController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/token/JwtTokenProvider.java
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/MemberErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberCommand.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/dto/MemberInfo.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/member/persistent/MemberRepository.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberApiSpec.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/MemberController.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberRequest.java
  src/main/java/com/sparksInTheStep/webBoard/member/presentation/dto/MemberResponse.java
  src/main/java/com/sparksInTheStep/webBoard/post/application/PostService.java
  src/main/java/com/sparksInTheStep/webBoard/post/application/dto/PostCommand.java
  src/main/java/com/sparksInTheStep/webBoard/post/application/dto/PostInfo.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/Post.java
  src/main/java/com/sparksInTheStep/webBoard/post/presentation/dto/PostRequest.java
  src/main/java/com/sparksInTheStep/webBoard/post/presentation/dto/PostResponse.java
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/login.js
  src/main/resources/templates/loginPage.html
Labels: 🛠 feat, 📞 API, 🏸 refactor

#98 [Feat] db 연결을 위한 설정
  src/main/resources/application.properties
  src/main/resources/sql/data.sql
Labels: 🛠 feat, 🧷 Git

#105 Main Branch add
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminApiController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/AuthController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/token/JwtTokenProvider.java
  src/main/java/com/sparksInTheStep/webBoard/comment/application/dto/CommentInfo.java
  src/main/java/com/sparksInTheStep/webBoard/global/errorHandling/errorCode/ProjectErrorCode.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/java/com/sparksInTheStep/webBoard/global/listener/TimeStamp.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/post/application/dto/PostInfo.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/Post.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/ProjectPost.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/Role.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/ProjectService.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectCommand.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectInfo.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/Project.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectRequest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/application/MemberServiceTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/domain/MemberTest.java
  src/test/java/com/sparksInTheStep/webBoard/auth/persistent/MemberRepositoryTest.java
Labels: 🛠 feat, 🧷 Git

#109 [Refactor] #108 시스템 전체 검토
  src/main/java/com/sparksInTheStep/webBoard/admin/presentation/AdminApiController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/presentation/AuthController.java
  src/main/java/com/sparksInTheStep/webBoard/auth/token/JwtTokenProvider.java
  src/main/java/com/sparksInTheStep/webBoard/comment/application/CommentService.java
  src/main/java/com/sparksInTheStep/webBoard/comment/application/dto/CommentInfo.java
  src/main/java/com/sparksInTheStep/webBoard/comment/domain/Comment.java
  src/main/java/com/sparksInTheStep/webBoard/comment/presentation/dto/CommentResponse.java
  src/main/java/com/sparksInTheStep/webBoard/global/baseEntity/TimeStamp.java
  src/main/java/com/sparksInTheStep/webBoard/global/filter/MemberArgumentResolver.java
  src/main/java/com/sparksInTheStep/webBoard/member/application/MemberService.java
  src/main/java/com/sparksInTheStep/webBoard/member/domain/Member.java
  src/main/java/com/sparksInTheStep/webBoard/post/application/PostService.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/Post.java
  src/main/java/com/sparksInTheStep/webBoard/post/domain/PostType.java
  src/main/java/com/sparksInTheStep/webBoard/post/presentation/PostController.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/ProjectService.java
  src/main/java/com/sparksInTheStep/webBoard/project/application/dto/ProjectCommand.java
  src/main/java/com/sparksInTheStep/webBoard/project/doamin/Project.java
  src/main/java/com/sparksInTheStep/webBoard/project/presentation/dto/ProjectRequest.java
  src/main/resources/static/js/login.js
Labels: 🏸 refactor
